# Generated by Django 2.2.6 on 2019-12-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskreportapp', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
"""
CREATE PROCEDURE generate_brands()
BEGIN
  DECLARE i INT DEFAULT 0;
  DECLARE j INT DEFAULT 0;
  SELECT @lid:=LAST_INSERT_ID();
  SET @seed = rand(round(rand(@lid)*4294967296))*36+1;
  CREATE TEMPORARY TABLE new_tbl ENGINE=MEMORY SELECT `name` FROM `diskreportapp_brand` LIMIT 0;
  WHILE i < 5 DO
    SET @out_str = '';
    SET j = 0;
    WHILE j < 16 DO
      SET @out_str = concat(@out_str, substring('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', rand(@seed:=round(rand(@seed)*4294967296))*36+1, 1));
      SET j = j + 1;
    END WHILE;
    INSERT IGNORE INTO new_tbl (`name`) VALUES (@out_str);
    SET i = i + 1;
  END WHILE;
  INSERT IGNORE INTO `diskreportapp_brand` (`name`) SELECT * FROM new_tbl;
  DROP TABLE new_tbl;
END
"""
        ),
        migrations.RunSQL(
"""
CREATE PROCEDURE generate_drives()
BEGIN
  DECLARE i INT DEFAULT 0;
  SELECT @lid:=LAST_INSERT_ID();
  SET @seed = rand(round(rand(@lid)*4294967296))*36+1;
  CREATE TEMPORARY TABLE new_tbl ENGINE=MEMORY SELECT `disk_type`, `capacity`, `size`, `interface_type`, `brand_id` FROM `diskreportapp_drive` LIMIT 0;
  WHILE i < 20 DO
    INSERT IGNORE INTO new_tbl (`disk_type`, `capacity`, `size`, `interface_type`, `brand_id`) VALUES (
      round(rand(@seed:=round(rand(@seed)*4294967296))*1.9),
      16*POW(2,round(rand(@seed:=round(rand(@seed)*4294967296))*8)),
      round(rand(@seed:=round(rand(@seed)*4294967296))*12)+8,
      round(rand(@seed:=round(rand(@seed)*4294967296))*4.9),
      round(rand(@seed:=round(rand(@seed)*4294967296))*5)+1
    );
    SET i = i + 1;
  END WHILE;
  INSERT IGNORE INTO `diskreportapp_drive` (`disk_type`, `capacity`, `size`, `interface_type`, `brand_id`) SELECT * FROM new_tbl;
  DROP TABLE new_tbl;
END
"""
        ),
        migrations.RunSQL(
"""
CREATE PROCEDURE generate_drivesales()
BEGIN
  DECLARE i INT DEFAULT 0;
  SELECT @lid:=LAST_INSERT_ID();
  SET @seed = rand(round(rand(@lid)*4294967296))*36+1;
  CREATE TEMPORARY TABLE new_tbl ENGINE=MEMORY SELECT `date`, `drive_id` FROM `diskreportapp_drivesale` LIMIT 0;
  WHILE i < 100000 DO
    INSERT IGNORE INTO new_tbl (`date`, `drive_id`) VALUES (
      NOW() - INTERVAL round(rand(@seed:=round(rand(@seed)*4294967296))*100000) DAY,
      round(rand(@seed:=round(rand(@seed)*4294967296))*10)+1
    );
    SET i = i + 1;
  END WHILE;
  INSERT IGNORE INTO `diskreportapp_drivesale` (`date`, `drive_id`) SELECT * FROM new_tbl;
  DROP TABLE new_tbl;
END
"""
        ),
        migrations.RunSQL(
"""
CREATE PROCEDURE archive_sales()
BEGIN
  INSERT INTO `diskreportapp_drivesalecompressed` (`id`, `date`, `drive_id`) SELECT * FROM `diskreportapp_drivesale` WHERE DATE(`date`) < DATE_SUB(CURDATE(), INTERVAL 1000 DAY);
  DELETE FROM `diskreportapp_drivesale` WHERE DATE(`date`) < DATE_SUB(CURDATE(), INTERVAL 1000 DAY);
  OPTIMIZE TABLE `diskreportapp_drivesale`;
END
"""
        ),
        migrations.RunSQL(
            "CALL generate_brands()",
        ),
        migrations.RunSQL(
            "CALL generate_drives()",
        ),
    ]
