# Generated by Django 2.2.6 on 2019-11-27 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Brand object',
                'verbose_name_plural': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_type', models.PositiveSmallIntegerField(choices=[(0, 'SSD'), (1, 'HDD')], verbose_name='type')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='capacity')),
                ('size', models.PositiveSmallIntegerField(verbose_name='size')),
                ('interface_type', models.PositiveSmallIntegerField(choices=[(0, 'Other'), (1, 'USB'), (2, 'SCSI'), (3, 'SAS'), (4, 'IDE')], default=0, verbose_name='interface_type')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diskreportapp.Brand', verbose_name='brand')),
            ],
            options={
                'verbose_name': 'Drive object',
                'verbose_name_plural': 'drives',
                'ordering': ['brand', 'disk_type', 'capacity', 'size', 'interface_type'],
            },
        ),
    ]
