# Generated by Django 2.2.6 on 2019-11-27 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diskreportapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='sale date')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diskreportapp.Drive', verbose_name='drive')),
            ],
            options={
                'verbose_name': 'Drive sale object',
                'verbose_name_plural': 'drive sales',
                'ordering': ['drive', 'date'],
            },
        ),
    ]
